parameters:

services:
    swiftmailer.transport.eventdispatcher.accord_mandrill: 
        class: Swift_Events_SimpleEventDispatcher
    
    swiftmailer.mailer.transport.accord_mandrill:
        class: Accord\MandrillSwiftMailer\SwiftMailer\MandrillTransport
        arguments:
            - @swiftmailer.transport.eventdispatcher.accord_mandrill
